export { Instruction } from './base';
export { Binop, BinopType } from './binop';
export { Branch } from './branch';
export { Call, CallType } from './call';
export { Cast, CastType } from './cast';
export { ExtractValue } from './extractvalue';
export { GetElementPtr } from './getelementptr';
export { ICmp, ICmpPredicate } from './icmp';
export { InsertValue } from './insertvalue';
export { Jump } from './jump';
export { Load } from './load';
export { IPhiEdge, Phi } from './phi';
export { Ret } from './ret';
export { Store } from './store';
export { ISwitchCase, Switch } from './switch';
